version: 2
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test-python3:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    working_directory: "~/gears"

    docker:
      - image: python:2-alpine3.7

    steps:
      - checkout

      - restore_cache:
          key: gears-1-{{ checksum "setup.py"}}

      - run:
          name: Install Dependencies
          command: pip install -e .

      - save_cache:
          key: gears-1-{{ checksum "setup.py"}}
          paths:
              - "~/.cache/pip"

      - run:
          name: Validation suite
          command: examples/test.py validation

      - run:
          name: Exchange litmus test
          command: .circleci/litmus-test.sh

  test-python3:
    docker:
      - image: python:3-alpine3.7

    steps:
      - checkout

      - restore_cache:
          key: gears-1-{{ checksum "setup.py"}}

      - run:
          name: Install Dependencies
          command: pip install -e .

      - save_cache:
          key: gears-1-{{ checksum "setup.py"}}
          paths:
              - "~/.cache/pip"

      - run:
          name: Validation suite
          command: examples/test.py validation

      - run:
          name: Exchange litmus test
          command: .circleci/litmus-test.sh
